# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       phonon

# >> macros
# << macros

Summary:    Phonon multimedia framework
Version:    4.4.3
Release:    1
Epoch:      1
Group:      System/Libraries
License:    LGPLv2.1
URL:        http://phonon.kde.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  phonon.yaml
Patch0:     01_phonon-inc.patch
Patch1:     02_no_rpath.patch
Patch2:     03_phonon_is_not_forced_in_KDE.patch
Patch3:     0001-With-new-glib-you-can-only-include-glib.h.patch
Patch4:     0001-Fix-compile-pow-missing.patch
Patch5:     0002-Add-support-for-nvxvimagesink.patch
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(QtOpenGL)
BuildRequires:  pkgconfig(alsa)
BuildRequires:  pkgconfig(gl)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(gstreamer-0.10)
BuildRequires:  pkgconfig(gstreamer-plugins-base-0.10)
BuildRequires:  pkgconfig(libpulse)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xcb)
BuildRequires:  automoc
BuildRequires:  cmake
BuildRequires:  gcc-c++

%description
Phonon is the Qt 4 multimedia API, which provides a task-oriented abstraction
layer for capturing, mixing, processing, and playing audio and video content.


%package -n lib%{name}-devel
Summary:    Phonon multimedia framework - development files
Group:      Development/Libraries
Requires:   %{name} = %{epoch}:%{version}-%{release}
Requires:   lib%{name}4 = %{?epoch:%{epoch}:}%{version}
Requires:   libqt-devel >= 4.7.0

%description -n lib%{name}-devel
Phonon is the Qt 4 multimedia API, which provides a task-oriented abstraction
layer for capturing, mixing, processing, and playing audio and video content.

This package contains the development files needed to build Qt 4 applications
using Phonon cross-platform multimedia framework.


%package -n lib%{name}4
Summary:    Phonon multimedia framework - runtime files
Group:      System/Libraries
Requires:   %{name} = %{epoch}:%{version}-%{release}
Requires:   %{name}-backend
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n lib%{name}4
Phonon is the Qt 4 multimedia API, which provides a task-oriented abstraction
layer for capturing, mixing, processing, and playing audio and video content.

This package contains the core library of the Phonon cross-platform multimedia
framework for Qt 4. It is required to run applications that use Phonon.


%package -n %{name}-backend-gstreamer
Summary:    Phonon GStreamer 0.10.x backend
Group:      Applications/Multimedia
Requires:   %{name} = %{epoch}:%{version}-%{release}
Requires:   gst-plugins-base
Provides:   %{name}-backend = %{?epoch:%{epoch}:}%{version}

%description -n %{name}-backend-gstreamer
Phonon is the Qt 4 multimedia API, which provides a task-oriented abstraction
layer for capturing, mixing, processing, and playing audio and video content.

This package contains GStreamer 0.10.x backend for Phonon.

You should install gst-plugins-good package to get support for playing popular
free multimedia formats and gstreamer0.10-plugins-ugly to get support for
popular MPEG audio formats like MP3.


%prep
%setup -q -n %{name}-%{version}/%{name}

# 01_phonon-inc.patch
%patch0 -p1
# 02_no_rpath.patch
%patch1 -p1
# 03_phonon_is_not_forced_in_KDE.patch
%patch2 -p1
# 0001-With-new-glib-you-can-only-include-glib.h.patch
%patch3 -p1
# 0001-Fix-compile-pow-missing.patch
%patch4 -p1
# 0002-Add-support-for-nvxvimagesink.patch
%patch5 -p1
# >> setup
# << setup

%build
# >> build pre
mkdir %{_target_platform}
cd %{_target_platform} && cmake .. -DCMAKE_INSTALL_PREFIX="%{_prefix}" -DCMAKE_C_COMPILER:FILEPATH="cc" -DCMAKE_CXX_COMPILER:FILEPATH="g++" -DCMAKE_C_FLAGS="%{optflags}" -DCMAKE_CXX_FLAGS="%{optflags}" -DCMAKE_SKIP_RPATH=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_SKIP_RPATH:BOOL=OFF -DCMAKE_USE_RELATIVE_PATHS=ON -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined" -DCMAKE_MODULE_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined" -DCMAKE_EXE_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined" -DLIB_INSTALL_DIR=%{_libdir} -DPLUGIN_INSTALL_DIR=%{_libdir}/qt4/ -DUSE_INSTALL_PLUGIN=TRUE
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
make -C %{_target_platform} install DESTDIR=%{buildroot}
# libphonon-devel symlink - headers compatibility
mkdir %{buildroot}%{_includedir}/qt4
pushd %{buildroot}%{_includedir}/qt4; ln -sf ../phonon
# Remove unpackaged files
rm -f %{buildroot}%{_libdir}/libphononexperimental.*
rm -rf %{buildroot}%{_includedir}/KDE/Phonon/Experimental
rm -rf %{buildroot}%{_includedir}/phonon/experimental
popd
# << install post

%post -n lib%{name}4 -p /sbin/ldconfig

%postun -n lib%{name}4 -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
# << files

%files -n lib%{name}-devel
%defattr(-,root,root,-)
# >> files lib%{name}-devel
%{_includedir}/phonon/AbstractAudioOutput
%{_includedir}/phonon/AbstractMediaStream
%{_includedir}/phonon/AbstractVideoOutput
%{_includedir}/phonon/AddonInterface
%{_includedir}/phonon/AudioCaptureDevice
%{_includedir}/phonon/AudioCaptureDeviceModel
%{_includedir}/phonon/AudioChannelDescription
%{_includedir}/phonon/AudioChannelDescriptionModel
%{_includedir}/phonon/AudioOutput
%{_includedir}/phonon/AudioOutputDevice
%{_includedir}/phonon/AudioOutputDeviceModel
%{_includedir}/phonon/AudioOutputInterface
%{_includedir}/phonon/AudioOutputInterface40
%{_includedir}/phonon/AudioOutputInterface42
%{_includedir}/phonon/BackendCapabilities
%{_includedir}/phonon/BackendInterface
%{_includedir}/phonon/Effect
%{_includedir}/phonon/EffectDescription
%{_includedir}/phonon/EffectDescriptionModel
%{_includedir}/phonon/EffectInterface
%{_includedir}/phonon/EffectParameter
%{_includedir}/phonon/EffectWidget
%{_includedir}/phonon/Global
%{_includedir}/phonon/MediaController
%{_includedir}/phonon/MediaNode
%{_includedir}/phonon/MediaObject
%{_includedir}/phonon/MediaObjectInterface
%{_includedir}/phonon/MediaSource
%{_includedir}/phonon/ObjectDescription
%{_includedir}/phonon/ObjectDescriptionData
%{_includedir}/phonon/ObjectDescriptionModel
%{_includedir}/phonon/ObjectDescriptionModelData
%{_includedir}/phonon/Path
%{_includedir}/phonon/Phonon/AbstractAudioOutput
%{_includedir}/phonon/Phonon/AbstractMediaStream
%{_includedir}/phonon/Phonon/AbstractVideoOutput
%{_includedir}/phonon/Phonon/AddonInterface
%{_includedir}/phonon/Phonon/AudioDevice
%{_includedir}/phonon/Phonon/AudioDeviceEnumerator
%{_includedir}/phonon/Phonon/AudioOutput
%{_includedir}/phonon/Phonon/AudioOutputDevice
%{_includedir}/phonon/Phonon/AudioOutputDeviceModel
%{_includedir}/phonon/Phonon/AudioOutputInterface
%{_includedir}/phonon/Phonon/BackendCapabilities
%{_includedir}/phonon/Phonon/BackendInterface
%{_includedir}/phonon/Phonon/Effect
%{_includedir}/phonon/Phonon/EffectDescription
%{_includedir}/phonon/Phonon/EffectDescriptionModel
%{_includedir}/phonon/Phonon/EffectInterface
%{_includedir}/phonon/Phonon/EffectParameter
%{_includedir}/phonon/Phonon/EffectWidget
%{_includedir}/phonon/Phonon/Global
%{_includedir}/phonon/Phonon/MediaController
%{_includedir}/phonon/Phonon/MediaNode
%{_includedir}/phonon/Phonon/MediaObject
%{_includedir}/phonon/Phonon/MediaObjectInterface
%{_includedir}/phonon/Phonon/MediaSource
%{_includedir}/phonon/Phonon/ObjectDescription
%{_includedir}/phonon/Phonon/ObjectDescriptionModel
%{_includedir}/phonon/Phonon/Path
%{_includedir}/phonon/Phonon/PlatformPlugin
%{_includedir}/phonon/Phonon/SeekSlider
%{_includedir}/phonon/Phonon/StreamInterface
%{_includedir}/phonon/Phonon/VideoPlayer
%{_includedir}/phonon/Phonon/VideoWidget
%{_includedir}/phonon/Phonon/VideoWidgetInterface
%{_includedir}/phonon/Phonon/VolumeFaderEffect
%{_includedir}/phonon/Phonon/VolumeFaderInterface
%{_includedir}/phonon/Phonon/VolumeSlider
%{_includedir}/phonon/PlatformPlugin
%{_includedir}/phonon/SeekSlider
%{_includedir}/phonon/StreamInterface
%{_includedir}/phonon/SubtitleDescription
%{_includedir}/phonon/SubtitleDescriptionModel
%{_includedir}/phonon/VideoCaptureDevice
%{_includedir}/phonon/VideoCaptureDeviceModel
%{_includedir}/phonon/VideoPlayer
%{_includedir}/phonon/VideoWidget
%{_includedir}/phonon/VideoWidgetInterface
%{_includedir}/phonon/VideoWidgetInterface44
%{_includedir}/phonon/VideoWidgetInterfaceLatest
%{_includedir}/phonon/VolumeFaderEffect
%{_includedir}/phonon/VolumeFaderInterface
%{_includedir}/phonon/VolumeSlider
%{_includedir}/phonon/abstractaudiooutput.h
%{_includedir}/phonon/abstractmediastream.h
%{_includedir}/phonon/abstractvideooutput.h
%{_includedir}/phonon/addoninterface.h
%{_includedir}/phonon/audiodataoutput.h
%{_includedir}/phonon/audiodataoutputinterface.h
%{_includedir}/phonon/audiooutput.h
%{_includedir}/phonon/audiooutputinterface.h
%{_includedir}/phonon/backendcapabilities.h
%{_includedir}/phonon/backendinterface.h
%{_includedir}/phonon/effect.h
%{_includedir}/phonon/effectinterface.h
%{_includedir}/phonon/effectparameter.h
%{_includedir}/phonon/effectwidget.h
%{_includedir}/phonon/globalconfig.h
%{_includedir}/phonon/mediacontroller.h
%{_includedir}/phonon/medianode.h
%{_includedir}/phonon/mediaobject.h
%{_includedir}/phonon/mediaobjectinterface.h
%{_includedir}/phonon/mediasource.h
%{_includedir}/phonon/objectdescription.h
%{_includedir}/phonon/objectdescriptionmodel.h
%{_includedir}/phonon/path.h
%{_includedir}/phonon/phonon
%{_includedir}/phonon/phonon_export.h
%{_includedir}/phonon/phonondefs.h
%{_includedir}/phonon/phononnamespace.h
%{_includedir}/phonon/platformplugin.h
%{_includedir}/phonon/pulsesupport.h
%{_includedir}/phonon/seekslider.h
%{_includedir}/phonon/streaminterface.h
%{_includedir}/phonon/videoplayer.h
%{_includedir}/phonon/videowidget.h
%{_includedir}/phonon/videowidgetinterface.h
%{_includedir}/phonon/volumefadereffect.h
%{_includedir}/phonon/volumefaderinterface.h
%{_includedir}/phonon/volumeslider.h
%{_includedir}/qt4/phonon
%{_libdir}/libphonon.so
%{_libdir}/pkgconfig/phonon.pc
%{_datadir}/dbus-1/interfaces/org.kde.Phonon.AudioOutput.xml
%{_datadir}/qt4/mkspecs/modules/qt_phonon.pri
# << files lib%{name}-devel

%files -n lib%{name}4
%defattr(-,root,root,-)
# >> files lib%{name}4
%{_libdir}/libphonon.so.4
%{_libdir}/libphonon.so.4.*
# << files lib%{name}4

%files -n %{name}-backend-gstreamer
%defattr(-,root,root,-)
# >> files %{name}-backend-gstreamer
%{_libdir}/qt4/plugins/phonon_backend/phonon_gstreamer.so
%{_datadir}/kde4/services/phononbackends/gstreamer.desktop
# << files %{name}-backend-gstreamer
